# Generated by Django 4.1 on 2023-02-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_api', '0002_rename_people_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
